### ISSUE TITLE
Trailing whitespaces on docs outside of scope

### ISSUE THREAD

**Issue by ttomdewit** [Mixd/frontend-framework#15]
# Trailing whitespaces
Delete all whitespace (spaces that shouldn't be in the code) of content within Wordpress-admin. For example, ```helper-functions.php``` on mixd.co.uk has various trailing spaces that can (and probably should) be removed.

It's not a critical change, but it's convenient to have a task running that makes sure all code ends up clean.

**Comment by lukewhitehouse** [comment]
Wrong framework @ttomdewit ;)
